### ISSUE TITLE
Suggestion: Upgrade from Qk/Quik to Mr. Hyde Wizard Scripts - Why? Why not?

### ISSUE THREAD

**Issue by geraldb** [StartZeroGnu/sz-jekyll-flex#1]
Hello,
  As posted in your last pull request (on the quik/scrits repo). FYI: If you configure a Jekyll theme - it might be easier to use Mr Hyde (builds on Qk/Quik) e.g. no need to bundle your theme as a template (you can auto-configure your _config.yml etc. in config block etc.) - let me know if you want to move your script over to https://github.com/mrhydescripts/scripts Keep it up. Cheers.

**Comment by StartZeroGnu** [comment]
Hi,
and would be available in the 2 sites with only 1 repo? if the answer is yes, go ahead.

Thanks.

**Comment by geraldb** [comment]
@StartZeroGnu  If it is a jekyll theme quick starter than please use mrhyde - it offers more functionality and you do NOT need to duplicate your theme repo e.g.  change

```
 use "StartZeroGnu/sz-jekyll-flex"   
```

to

```
install_theme "StartZeroGnu/sz-jekyll-flex"
```

and it will also configure your _config.yml, for example, with your settings e.g. mrhyde knows about _config.yml (it's built-in).  Qk/quick is for "generic" scaffolding almost anything incl. new themes / gems / etc. (not really for using existing jekyll themes).  PS: mrhyde uses the quik gem / machinery but the scripts repos are NOT linked.

**Comment by StartZeroGnu** [comment]
@geraldb have to forgive me, but my English is not very good and google does not help me. I do not know if I understand you correctly.

have I to stop using QK because it is created for another purpose, and have I to use Mr.Hyde that is more suited to my project?

**Comment by geraldb** [comment]
@StartZeroGnu   The point is - It's easier / better to use Mr. Hyde (it is a qk/quik extension!) for Jekyll themes - that what it is here for.  It's up to you. Thanks for trying Qk/Quik. Cheers.

**Comment by StartZeroGnu** [comment]
The objective of this project is to create a scaffold for jekyll, and then create a theme from the scaffold. It is true that I have precipitated, and was almost becoming a theme, but the main objective is to create a scaffold (as now).

Now I will create a theme from scaffolding on a new repo and I'll upload to Mr.Hyde

Thanks for all @geraldb

**Comment by geraldb** [comment]
@StartZeroGnu  Thanks for the update and clarifications. No worries. I close the issue. Keep it up. Cheers.
